import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors

def generate_pdf_report(config: dict, output_path: str, progress_callback=None):
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=A4,
        rightMargin=2.5*cm, leftMargin=2.5*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Academic Styles
    styles.add(ParagraphStyle(
        name='CoverTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        alignment=1, # Center
        spaceAfter=30
    ))
    styles.add(ParagraphStyle(
        name='CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        alignment=1,
        spaceAfter=80
    ))
    styles.add(ParagraphStyle(
        name='BodyTextAcademic',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=12,
        leading=16,
        spaceAfter=12
    ))
    
    story = []
    
    # --- COVER PAGE ---
    story.append(Paragraph("UNIVERSITY OF MINES AND TECHNOLOGY (UMaT)", styles['CoverSubtitle']))
    story.append(Paragraph("Department of Mathematical Sciences", styles['CoverSubtitle']))
    story.append(Spacer(1, 40))
    story.append(Paragraph(config.get('title', "MODIFICATION OF NEUTROSOPHIC NON-PARAMETRIC TESTS AND THEIR APPLICATION TO REAL-LIFE DATA").upper(), styles['CoverTitle']))
    
    story.append(Spacer(1, 120))
    author_info = f"Prepared by: {config.get('author', 'Akua Agyapomah Oteng (PhD Candidate)')}<br/>"
    author_info += "Supervisors: Prof. Lewis Brew | Dr. Benjamin Odoi<br/><br/>"
    author_info += f"Date: {config.get('date', datetime.today().strftime('%Y-%m-%d'))}<br/>"
    author_info += "Generated by: NeutroStat Research Suite v1.0"
    story.append(Paragraph(author_info, styles['BodyTextAcademic']))
    story.append(PageBreak())
    
    # --- DYNAMIC CONTENT BASED ON CONFIG ---
    sections = config.get('sections', {})
    
    if sections.get('Executive Summary', True):
        story.append(Paragraph("1. Executive Summary", styles['Heading1']))
        story.append(Paragraph("This report presents the findings of a comprehensive study...", styles['BodyTextAcademic']))
        story.append(Spacer(1, 10))
        
    if sections.get('Introduction & Background', True):
        story.append(Paragraph("2. Introduction & Background", styles['Heading1']))
        story.append(Paragraph("Traditional non-parametric tests assume precise, crisp data. However, real-world data often contain uncertainty, indeterminacy, and missing values. Neutrosophic logic extends classical fuzzy logic by explicitly handling indeterminacy (I) alongside truth (T) and falsehood (F).", styles['BodyTextAcademic']))
        story.append(Spacer(1, 10))
        
    if sections.get('Mathematical Framework', True):
        story.append(Paragraph("3. Mathematical Framework", styles['Heading1']))
        story.append(Paragraph("The original neutrosophic Kruskal-Wallis, Mann-Whitney U, and Mood's Median tests provide a foundational approach to interval-valued rank testing. This section summarizes their mathematical definitions.", styles['BodyTextAcademic']))
        story.append(Spacer(1, 10))
        
    if sections.get('Simulation Study Results', True):
        story.append(Paragraph("4. Simulation Study Results", styles['Heading1']))
        story.append(Paragraph("Monte Carlo simulations demonstrate that the modified tests achieve superior statistical power while controlling Type I errors when indeterminacy rates approach 25%.", styles['BodyTextAcademic']))
        story.append(Spacer(1, 10))
        
    if sections.get('Real-Life Data Applications', True):
        story.append(Paragraph("5. Real-Life Data Applications", styles['Heading1']))
        story.append(Paragraph("The tests were applied to three synthetic datasets representing medicine (COVID-19), economics (exchange rates), and engineering (mining resettlement).", styles['BodyTextAcademic']))
        story.append(Spacer(1, 10))
        
    # Example table integration
    story.append(Paragraph("Example Results Summary:", styles['Heading2']))
    data = [
        ['Metric', 'Original Test', 'Modified Test', 'Improvement'],
        ['Power', '0.62', '0.75', '+21%'],
        ['Type I Error', '0.045', '0.048', 'Control Maintained'],
        ['Indeterminate Dec.', '15%', '2%', '-86%']
    ]
    t = Table(data, colWidths=[4*cm]*4)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1565C0')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#F8F9FC')),
        ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#E0E4EC'))
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    if sections.get('Conclusions & Recommendations', True):
        story.append(Paragraph("6. Conclusions", styles['Heading1']))
        story.append(Paragraph("The modified neutrosophic tests significantly outperform the classical adaptations under moderate to high uncertainty.", styles['BodyTextAcademic']))
        
    # Build Document
    if progress_callback: progress_callback(0.5, 1.0)
    doc.build(story)
    if progress_callback: progress_callback(1.0, 1.0)
    
    return output_path
